name: Android CI

on:
  push:
    branches: [ "master" ]
#  pull_request:
#    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

#    - name: Build with Gradle
#      run: ./gradlew build

    - name: Setup Gradle Cache
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/**/*.kt') }}
#
#    - name: Make gradlew executable
#      run: chmod +x ./gradlew

#    - name: Generate app bundle.
#      run: ./gradlew app:bundleRelease --stacktrace

#    - name: Generate app APK.
#      run: ./gradlew assembleDebug --stacktrace

#    - name: Upload Bundle
#      uses: actions/upload-artifact@v2
#      with:
#        name: signed_app_bundle
#        path: app/build/outputs/bundle/release/app-release.aab

#    - name: Upload APK to Github Artifacts
#      uses: actions/upload-artifact@v2
#      with:
#        name: demo.apk
#        path: app/build/outputs/apk/debug/app-debug.apk
#
#    - name: Download APK from build
#      uses: actions/download-artifact@v1
#      with:
#        name: demo.apk
#        path: app/build/outputs/apk/debug/app-debug.apk
